<a href="https://colab.research.google.com/github/nitishxthakur/DataLab/blob/main/Multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas  as pd
import numpy as np
from sklearn import linear_model
from matplotlib import pyplot as plt


In [57]:
df=pd.read_csv('/content/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [58]:
import math
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [59]:
model=linear_model.LinearRegression()
model.fit(df.drop('price', axis=1), df.price)

LinearRegression()

In [60]:
model.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [61]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [62]:
model.intercept_

221323.00186540396

In [63]:
new_df=pd.read_csv('/content/hiring.csv')
new_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [65]:
new_df.experience=new_df.experience.fillna('Zero')
new_df['test_score(out of 10)']=new_df['test_score(out of 10)'].fillna(new_df['test_score(out of 10)'].median())
new_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [66]:
!pip install word2number

from word2number import w2n

# Convert the 'experience' column to string type before applying word_to_num
new_df.experience = new_df.experience.astype(str)
new_df.experience = new_df.experience.apply(w2n.word_to_num)

In [67]:
new_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [68]:
model.fit(new_df.drop('salary($)', axis=1), new_df['salary($)'])

LinearRegression()

In [69]:
model.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [70]:
model.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])